name: hola mundo

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje Hola Mundo
        run: echo "Hola Mundo, Andres"
