name: Multiples jobs

on:
  workflow_dispatch

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime nombre job
        run: echo Job 1

  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime nombre job
        run: echo Job 2

  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime nombre job
        run: echo Job 3

  job-dependiente:
    runs-on: ubuntu-latest
    needs: [job-1, job-3] #espera que job terminen antes de comenzar
    steps:
      - name: Imprime nombre job
        run: echo Job Dependiente
